version: '3.8'

services:
  # web:
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - "${BOT_PORT}:${BOT_PORT}"
  #   volumes:
  #     - .:/usr/src/app
  #   command: air ./cmd/main.go -b 0.0.0.0
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
      - .env